-- * BUY ITEMS * --

-- * TO ADD DECIMAL PRICES TO THE RANDOMPRICE DO IT LIKE THIST math.random(30, 50) / 100 >> this will equal to 0.30 to 0.50 or math.random(300, 500) / 100 will equal to 3.00 to 5.00

-- * THESE ARE JUST EXAMPLES YOU MUST CONFIGURE YOUR OWN STORES *--
Config.BuyItems = {
    Valentine = {

        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "Buy bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "Buy Knife",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },

    Rhodes = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },

    Strawberry = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },

    Blackwater = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },
    Armadillo = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },
    Tumbleweed = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },
    StDenis = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },
    Vanhorn = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        }
    },
    BlackwaterFishing = {
        {
            itemLabel = "Fishing rod",
            itemName = "WEAPON_FISHINGROD",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell Fishing rod",
            category = "tools",
            weapon = true,
            itemLimit = 0,
        },
        {
            itemLabel = "Bread bait",
            itemName = "p_baitBread01x",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "Bread bait",
            category = "bait",
            itemLimit = 0,
        },

        {
            itemLabel = "Corn bait",
            itemName = "p_baitCorn01x",
            currencyType = "cash",
            buyprice = 35,
            randomprice = math.random(25, 40),
            desc = "Corn bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Cheese bait",
            itemName = "p_baitCheese01x",
            currencyType = "cash",
            buyprice = 45,
            randomprice = math.random(35, 50),
            desc = "Cheese bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Worm bait",
            itemName = "p_baitWorm01x",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 60),
            desc = "Worm bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Cricket bait",
            itemName = "p_baitCricket01x",
            currencyType = "cash",
            buyprice = 60,
            randomprice = math.random(50, 65),
            desc = "Cricket bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Crawdad bait",
            itemName = "p_crawdad01x",
            currencyType = "cash",
            buyprice = 70,
            randomprice = math.random(60, 75),
            desc = "Crawdad bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Dragonfly bait",
            itemName = "p_finishedragonfly01x",
            currencyType = "cash",
            buyprice = 80,
            randomprice = math.random(70, 90),
            desc = "Dragonfly bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Fish lure",
            itemName = "p_FinisdFishlure01x",
            currencyType = "cash",
            buyprice = 100,
            randomprice = math.random(90, 110),
            desc = "Fish lure",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Legendary Dragonfly bait",
            itemName = "p_finishedragonflylegendary01x",
            currencyType = "cash",
            buyprice = 120,
            randomprice = math.random(110, 130),
            desc = "Legendary Dragonfly bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Legendary Fish lure",
            itemName = "p_finisdfishlurelegendary01x",
            currencyType = "cash",
            buyprice = 130,
            randomprice = math.random(120, 140),
            desc = "Legendary Fish lure",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Legendary Crawdad bait",
            itemName = "p_finishdcrawdlegendary01x",
            currencyType = "cash",
            buyprice = 140,
            randomprice = math.random(130, 150),
            desc = "Legendary Crawdad bait",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Lure Spinner V4",
            itemName = "p_lgoc_spinner_v4",
            currencyType = "cash",
            buyprice = 150,
            randomprice = math.random(140, 160),
            desc = "Lure Spinner V4",
            category = "bait",
            itemLimit = 0,
        },
        {
            itemLabel = "Lure Spinner V6",
            itemName = "p_lgoc_spinner_v6",
            currencyType = "cash",
            buyprice = 160,
            randomprice = math.random(150, 170),
            desc = "Lure Spinner V6",
            category = "bait",
            itemLimit = 0,
        },

    },
    Wapiti = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        --weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 50) / 100,
            desc = "Buy Pick Axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            buyprice = 20,
            randomprice = math.random(18, 22),
            desc = "Buy Tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Tropical Punch Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            buyprice = 25,
            randomprice = math.random(22, 28),
            desc = "Buy Wild Cider Moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Raspberry Ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 14),
            desc = "Buy Bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            buyprice = 5,
            randomprice = math.random(3, 7),
            desc = "Buy Chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Fruit Salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            buyprice = 18,
            randomprice = math.random(15, 20),
            desc = "Buy Game Meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(5, 8),
            desc = "Buy Pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Raspberry Water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            buyprice = 15,
            randomprice = math.random(12, 18),
            desc = "Buy Salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            buyprice = 7,
            randomprice = math.random(5, 9),
            desc = "Buy Kidney Beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            buyprice = 12,
            randomprice = math.random(10, 15),
            desc = "Buy Cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Blueberry Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chicken Pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            buyprice = 14,
            randomprice = math.random(12, 16),
            desc = "Buy Chocolate Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            buyprice = 8,
            randomprice = math.random(6, 10),
            desc = "Buy Donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Lemon Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Pound Cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(8, 12),
            desc = "Buy Sponge Cake",
            category = "food",
            itemLimit = 10,
        },
    }
}
