-- * SELL ITEMS  * --

-- * TO ADD DECIMAL PRICES TO THE RANDOMPRICE DO IT LIKE THIST math.random(30, 50) / 100 >> this will equal to 0.30 to 0.50 or math.random(300, 500) / 100 will equal to 3.00 to 5.00

-- * THESE ARE JUST EXAMPLES YOU MUST CONFIGURE YOUR OWN STORES *--

Config.SellItems = {
    Valentine = { -- name must be the same as  in the stores
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(5, 10),
            desc = "sell Knife",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    Rhodes = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    Strawberry = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    Blackwater = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    Armadillo = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    Tumbleweed = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    StDenis = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    Vanhorn = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
    BlackwaterFishing = {
        {
            itemLabel = "Smallmouth Bass", 
            itemName = "a_c_fishsmallmouthbass_01_ms",
            currencyType = "cash",
            sellprice  = 40,
            randomprice = math.random(30, 45),
            desc = "Smallmouth Bass",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Medium Bluegil", 
            itemName = "a_c_fishbluegil_01_ms",
            currencyType = "cash",
            sellprice  = 20,
            randomprice = math.random(15, 25),
            desc = "A medium-sized Bluegil fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Small Bluegil", 
            itemName = "a_c_fishbluegil_01_sm",
            currencyType = "cash",
            sellprice  = 10,
            randomprice = math.random(5, 15),
            desc = "A small Bluegil fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Medium Bullhead", 
            itemName = "a_c_fishbullheadcat_01_ms",
            currencyType = "cash",
            sellprice  = 25,
            randomprice = math.random(20, 30),
            desc = "A medium-sized Bullhead fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Small Bullhead", 
            itemName = "a_c_fishbullheadcat_01_sm",
            currencyType = "cash",
            sellprice  = 15,
            randomprice = math.random(10, 20),
            desc = "A small Bullhead fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Medium Pickerel", 
            itemName = "a_c_fishchainpickerel_01_ms",
            currencyType = "cash",
            sellprice  = 30,
            randomprice = math.random(25, 35),
            desc = "A medium-sized Pickerel fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Small Pickerel", 
            itemName = "a_c_fishchainpickerel_01_sm",
            currencyType = "cash",
            sellprice  = 15,
            randomprice = math.random(10, 20),
            desc = "A small Pickerel fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Largemouth Bass", 
            itemName = "a_c_fishlargemouthbass_01_ms",
            currencyType = "cash",
            sellprice  = 50,
            randomprice = math.random(45, 55),
            desc = "A large Largemouth Bass fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Medium Perch", 
            itemName = "a_c_fishperch_01_ms",
            currencyType = "cash",
            sellprice  = 25,
            randomprice = math.random(20, 30),
            desc = "A medium-sized Perch fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Small Perch", 
            itemName = "a_c_fishperch_01_sm",
            currencyType = "cash",
            sellprice  = 15,
            randomprice = math.random(10, 20),
            desc = "A small Perch fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Rainbow Trout", 
            itemName = "a_c_fishrainbowtrout_01_ms",
            currencyType = "cash",
            sellprice  = 35,
            randomprice = math.random(30, 40),
            desc = "A Rainbow Trout fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Medium Redfin Pickerel", 
            itemName = "a_c_fishredfinpickerel_01_ms",
            currencyType = "cash",
            sellprice  = 30,
            randomprice = math.random(25, 35),
            desc = "A medium-sized Redfin Pickerel fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Small Redfin Pickerel", 
            itemName = "a_c_fishredfinpickerel_01_sm",
            currencyType = "cash",
            sellprice  = 15,
            randomprice = math.random(10, 20),
            desc = "A small Redfin Pickerel fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Medium Rockbass", 
            itemName = "a_c_fishrockbass_01_ms",
            currencyType = "cash",
            sellprice  = 25,
            randomprice = math.random(20, 30),
            desc = "A medium-sized Rockbass fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Small Rockbass", 
            itemName = "a_c_fishrockbass_01_sm",
            currencyType = "cash",
            sellprice  = 15,
            randomprice = math.random(10, 20),
            desc = "A small Rockbass fish.",
            category = "fish",
            itemLimit = 0,
        },
        {
            itemLabel = "Sockeye Salmon", 
            itemName = "a_c_fishsalmonsockeye_01_ms",
            currencyType = "cash",
            sellprice  = 60,
            randomprice = math.random(55, 65),
            desc = "A Sockeye Salmon fish.",
            category = "fish",
            itemLimit = 0,
        },

    },
    Wapiti = {
        --meds
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        -- Weapons
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 15,
            randomprice = math.random(15, 20),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave
        },
        -- Tools
        {

            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 20,
            randomprice = math.random(15, 25) / 100,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

        -- Drinks
        {
            itemLabel = "Whisky",
            itemName = "whisky",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(5, 9),
            desc = "sell whisky",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Wine",
            itemName = "wine",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(8, 11),
            desc = "sell wine",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Vodka",
            itemName = "vodka",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(7, 10),
            desc = "sell vodka",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Beer",
            itemName = "beer",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell beer",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tequila",
            itemName = "tequila",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(9, 11),
            desc = "sell tequila",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Tropical Punch Moonshine",
            itemName = "tropicalPunchMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell tropical punch moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Wild Cider Moonshine",
            itemName = "wildCiderMoonshine",
            currencyType = "cash",
            sellprice = 12,
            randomprice = math.random(11, 14),
            desc = "sell wild cider moonshine",
            category = "drinks",
            itemLimit = 5,
        },
        {
            itemLabel = "Raspberry Ale",
            itemName = "raspberryale",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell raspberry ale",
            category = "drinks",
            itemLimit = 10,
        },

        -- Food Items
        {
            itemLabel = "Bluegill",
            itemName = "consumable_bluegil",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell bluegill",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Breakfast",
            itemName = "consumable_breakfast",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell breakfast",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Caramel",
            itemName = "consumable_caramel",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell caramel",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate",
            itemName = "consumable_chocolate",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell chocolate",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Coffee",
            itemName = "consumable_coffee",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 8),
            desc = "sell coffee",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Fruit Salad",
            itemName = "consumable_fruitsalad",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell fruit salad",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Game Meat",
            itemName = "consumable_game",
            currencyType = "cash",
            sellprice = 9,
            randomprice = math.random(8, 10),
            desc = "sell game meat",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Peach",
            itemName = "consumable_peach",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell peach",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pear",
            itemName = "consumable_pear",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(2, 4),
            desc = "sell pear",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Raspberry Water",
            itemName = "consumable_raspberrywater",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell raspberry water",
            category = "drinks",
            itemLimit = 10,
        },
        {
            itemLabel = "Salmon",
            itemName = "consumable_salmon",
            currencyType = "cash",
            sellprice = 8,
            randomprice = math.random(6, 9),
            desc = "sell salmon",
            category = "food",
            itemLimit = 5,
        },
        {
            itemLabel = "Kidney Beans (Can)",
            itemName = "consumable_kidneybeans_can",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell kidney beans",
            category = "food",
            itemLimit = 10,
        },

        -- Desserts
        {
            itemLabel = "Cheesecake",
            itemName = "cheesecake",
            currencyType = "cash",
            sellprice = 6,
            randomprice = math.random(5, 7),
            desc = "sell cheesecake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Blueberry Pie",
            itemName = "consumable_blueberrypie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell blueberry pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chicken Pie",
            itemName = "consumable_chickenpie",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chicken pie",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Chocolate Cake",
            itemName = "consumable_chocolatecake",
            currencyType = "cash",
            sellprice = 7,
            randomprice = math.random(6, 8),
            desc = "sell chocolate cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Cupcake",
            itemName = "consumable_cupcake",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell cupcake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Donut",
            itemName = "consumable_donut",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell donut",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Lemon Cake",
            itemName = "consumable_lemoncake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell lemon cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Pound Cake",
            itemName = "consumable_poundcake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell pound cake",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "Sponge Cake",
            itemName = "consumable_spongecake",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(4, 6),
            desc = "sell sponge cake",
            category = "food",
            itemLimit = 10,
        },


    },
}
